server:
  port: 7080

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7080/eureka/
#      defaultZone: http://localhost:7082/eureka/ # 此处改为第二个eureka-server地址
#      defaultZone: http://localhost:7081/eureka/,http://localhost:7082/eureka/ # 此处改为包含三个eureka-server
  server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false